İyi akşamlar iyi akşamlar iyi akşamlar
Eee pazar akşamı fikir coğrafyasında bir klasikle yani düşünce ufku la
birliktesiniz Eee bu akşam e düşünce ufku 167 programını size ulaştırıyor ve
yine her zamanki gibi çok farklı bir konu ve konukla birlikteyiz Eee Bugün
akşam Eee son yılların Belki de hayatımızın tam orta yerinde olan bazı
kavramları irdelemeye deşmeye çalışacağız Üstelik bu kavramlar için Eee Fikri anlamda
Eee her her durumda mücadele etmiş ve bu fikri planda e bazı kavramları
olgunlaştırmak için cehd etmiş bir isimle birlikteyiz tabiri caiz ise Eee
fikrinin Eee ya da eee tercihlerinin bir nevi bedelini de
Eee ödediğini düşündüğümüz bir isimle birlikteyiz müm Tezer Türköne Bey bugün
konuğumuz hocam hoş geldiniz Çok teşekkür ediyorum Baha Bey çok teşekkür ediyorum
Eee Bugün akşam Eee eee sizin de Eee afiş imizde gördüğünüz gibi eee bir özel
bir konuyla birlikteyiz Eee milliyetçi muhafazakar kodlar son dönemdeki
Eee her konuda her alanda karşımıza çıkan Beka milli yerlilik gibi kavramlar
üzerinden Eee siyasal tercihlerimiz tutun iç dünyamıza kadar her noktada baskın olan
bir fikri yapıyı Fikri bir ideolojiyi Eee burada tartışmaya ve anlamaya
çalışacağız Tolga ben böyle bir giriş yaptım istersen sana bırakayım Eyvallah Evet
eee şimdi bu akşam tabii e düşünce ufkunda biraz daha farklı bir program
yapabilir miyiz E biraz bunun merakı içindeyim Eee Çünkü Mümtazer Türköne hem
İslamcılık Eee hem de işte Türkçülük üzerine Türkiye'de milliyetçilik üzerine
En azından Eee nasıl diyelim içeriden mahallenin içinden gelen ve konuşan birisi ama biraz farklı artık Eee şeyler
duyuyoruz Sezer Bey'den doğru mu yani eee yani mahallenin biraz garibine giden
eee bir takım cümleler de duyuyoruz kendisinden o açıdan Eee önemli olduğunu
düşünüyorum Eee bu Tabii şöyle anlaşılsın da istemem Yani bizim izleyicilerimiz bu konuda
herhalde Eee gerekli bilgiye sahipler hani biz eee bir takım böyle ajitasyon yaparak
Eee böyle bir yayın ilkemiz yok Eee Dolayısıyla eee ya işte kim kendi
mahallesine vuruyorsa ya da kendini çok ciddi anlamda acımasızca eleştiriyorsa bu iyidir bunu alalım ve buradan bir
söylem geliştirelim gibi böyle bir tarzımız yok çünkü E ben de Eee Mümtazer beyi herhalde yaklaşık 25
sene önceden tanıyorum Eee Tabii Eee Çok zaman geçti üstünden ve Ama ben
kendisini Tabii takip ettim biliyorum Türkiye biliyor zaten eee ın da söylediği gibi hani nasıl
nasıl diyelim katılır mısınız münzer Bey yani duyguları da Eee fikirlerinin
içerisinde olan birisi diyebilir miyiz size yani hani böyle Salt rasyonel böyle
hani vardır ya bir akademisyen bir entelektüel böyle buz gibi buzdolabından çıkartılmış Yani gerçekten buna inanıyor
mu inanmıyor mu bu nedir filan böyle kararsız kaldığımız da olabiliyor ama ben sizi öyle bilmiyorum Mesela yani
Tolga Bey hayat boyunca buz gibi olmaya çalıştım ama çok Başaramadım onu
söyleyeyim yani buzdolabından çıkması gerekiyor bir
akademisyen olarak ürettiğiniz şeylerin ama galiba haklısınız bunu Başaramadım
Eee aslına bakarsanız bugün konuştuğumuz mevzu da öyle bir mevzu yani
milliyetçilik ulus devletin duygu durumu Ulus devlette yaşayan insanların bir
duygu durumunu tarif ediyorsunuz Bu duygu durumunu biz elimizden geldiği kadar Eee
kavramlara teorilere Eee karşılaştırmalara dökerek Eee
anlamaya ve Anlatmaya çalışıyoruz ve yani soğutmaya çalışıyoruz Çok sıcak bir
şey bizim biliyorsunuz Eee bu işin teorisiyle
Eee işte felsefesiyle uğraşanlar önce Cap canlı Fikri
düşünceyi öldürür şeye yatır otopsi masasına yatırır Ondan sonra elinde
bıçak didik didik eder bu akşam yapacağımız şey biraz da o Galiba
evet yani Türkiye yüzyılında rejimin milliyetçi muhafazakar kodları
diye çok zihin açıcı bir başlık koymuşsunuz
Kon şuradan Müsaade ederseniz Başlamak isterim Ben şimdi siz
biraz önce başta okudunuz Eee malum Eee Cumhurbaşkanlığı seviyesinde Yani devlet
M tepesinden E biz artık Türkiye yüzyılını yaşıyoruz yeni bir Yeni Yüzyıl
ve dolayısıyla bu Yüzyıl da Türkiye yüzyılı olarak ilan edildi Eee ve
Eee yeni anayasa tartışmalarından cumhurbaşkanlık sistemlerine varıncaya kadar ittifaklar Eee hakikaten Eee Türk
Türk siyasal hayatı Eee Alışık olmadığımız bir Eee nasıl düzleme zemine
oturuyor Eee ve dolayısıyla Eee çok açık ve net bir şekilde devlet bunu çok güçlü
bir şekilde de Eee kendi Eee yürüdüğü düzlemin yani
siyasetin Eee Tabiri caizse milliyetçi ve
muhafazakar bir zeminde Eee var olmasını istiyor Yani bütün siyasalın Yani bu sağ
ve sol fark etmiyor zaten böyle ama solun da Eee bu şekilde Eee olmasını
devletin güçlü sesiyle ilan ediyor şimdi ya bu bana ilginç geliyor yani Hem
sağdan ve hem soldan ittifaklı da biz bu tartışmaları görüyoruz birleşmeler ve
ayrışmalar da bu milliyetçi ve muhafazakar kodların ciddi anlamda çalıştığı Eee buu görüyoruz en son
cumhurbaşkanlığı seçiminde Eee işte Meral akşener'in ittifaklar ayrılması gibi yani siz Evet orada muhalif isiniz
ama ben burada muhalefet olarak sizinle birlikteyim Ama bu işte bir takım şeylere rejimin Eee kodlarına aykırı
dedi Yani ben de buna Katılıyorum dedi Ve ayrıldı sonra geri geldi vesaire yani
çok güçlü bir şekilde geliyor bu kodlar çalışıyor Eee bunu biraz deşmek
istiyoruz ama şuradan başlayabiliriz diye düşünüyorum yani hani buna kim karar veriyor böyle karar verenler var
mı Hani böyle komplo tartışmaları çok hoşumuza gider yani bir derin devlet bir
derin akıl kimdir bunlar siyasetin üstünde midir değil midir Bunu konuşalım
Ama öncelikle Eee bu milliyetçi muhafazakar kodlar ne demek yani bir
devlette rejim olarak bunlar nasıl çalışır bunu herhalde en iyi siz anlatırsınız diye düşünüyoruz bunu
anlayalım önce diye isim Eee Evet Eee Tolga Bey Yani şöyle bir başlangıç
yapmamız lazım Eee Türkiye'de Aslında Eee milliyetçilik muhafazakarlık Bazen
bu milliyetçilikle siyasal İslam diye de Eee gündeme getiriliyor bunun bir
sentezi mi bir evliliği mi bir simbiyoz hali mi Eee fiili olarak karşımızda
Duran fiili olarak yaşadığımız böyle bir şey var Eee milliyetçilikle
muhafazakarlık eee 1969 yılına kadar Eee Onlar zaten birlikteydi sonra ayrıştı
eee milliyetçilikle muhafazakarlık sanki bir simbiyoz halinde yaşıyor bu simbiyoz
bilirsiniz e tabiatta birbirinden beslenerek Eee birbirinin Hayat Eee
dinamiklerini kuvvetlendirerek yaşayan farklı canlılar Eee yani birlikte yaşamaktan İkisi de
Karlı çıkar böyle bir şey mi acaba eee ben hemen size Aslında sizin söyledi
ikinizde de var bir ortak payda ikisini de kesen ikisini de Eee aynı dairenin
içine alan bir devlet faktörü var devreye bu giriyor Eee sizin söylediğiniz Eee yani bir
devlet geleneği olan bir ülkede yaşıyoruz Biz Bunu yabana atamazsınız Eee hiçbir zaman devletsiz kalmamış bir
toplum Eee bu iyi mi kötü mü O ayrıca tartışılabilir
ama de bir devlet bilgisi bir devlet tecrübesi bir devlet pratiği Eee her
zaman herkesin ufkunda Eee gündelik hayatında siyasetle ilgili bir şey
söylerken düşünürken kafasının gerisinde bir yerlerde mutlaka var Eee şimdi devlet girince işin içine
zaten milliyetçilik dediğimiz ideoloji Eee işte 1648 vesal düzeni ulus
devletler çağı ve Ulus devletin ürünü Ulus devlete özgü bir duygu durumu
milliyetçilik bunu bir kavrama bir tanıma dökmeye
kalktığınız zaman Eee dağılır darmadağın olur Çünkü
Eee inanılmaz tasnif e şeyleri var çabaları var milliyetçiliğin Ama zamanla
zeminle değişen fakat hiçbir zaman Ulus devletle irtibatı ulus devletin çık karlarına uygun duruşu değişmeyen bir
duygu durumu olarak okumak lazım Eee bundan bir şey çıkmıyor çoğu zaman
sistematik bir ideoloji sistematik bir düşünce çıkmıyor ama duygu durumu olarak
zamana zemine göre değişiyor olaylara Eee farklı tepkiler veriyor bu
milliyetçiliğin içinde zaten vardı bu işte Devletin bekası söylemi Biz de
Osman Turan'ın Türk cihan hakimiyeti mefkuresi tarihiyle birlikte Eee
milliyetçiliğin Eee kavram dünyasını armağan ettiği Eee devlet ebedi müddet
devlet ebet müddet Eee anlayışı Eee zaten vardı fakat Türkiye'de siyasal
İslam muhafazakarlık tan önce siyasal İslam devlete devletin varlığına muhalif
bir hareketti Eee tam anlamıyla devletin karşısında E işte bir küfür Devleti
Burası bir Darül harp veya Darül Küfür gibi tartışmalar Eee vardı 1970'lerde
hatta 80'lerde devam eden Eee ve Eee son
derece muhalif oldukları bir Eee Kurumu yani devleti ele geçirdiler o devlet
iktidarına sahip oldular ve Eee 180 derece değişti Yani Türkiye'de hangi
ideoloji olursa olsun sol için de geçerli bu eee devlet iktidarıyla bir
şekilde temasa girdiği onun içine yerleştiği onun üstüne çıktığı zaman içine devlet diye bir şeytan giriyor ve
bambaşka bir şey çıkıyor ortaya bugün karşımızda olan da bu yani milliyetçilik
muhafazakarlığı birlikte zikrediyor ikisinin ortak paydası devlet
konusundaki anlayış Birliği Eee ve o devletin ihtiyaç duyduğu Duygu durumunu
İkisi de yansıtıyor Aslında İşte bundan Türkiye yüzyılı diye bir kavram çıkartıyor muhtemeldir ki çok Eee net
söyleyebilirim 5 yıl sonra böyle bir kavramı hiç kimse hatırlamayacak
Eee yani bunlar Eee İşte o Duygu durumuna uygun birileri oturuyor bir şeyler icat ediyorlar Bunlar tedavüle
giriyor kabul görüyor reddediliyor ama Eee herhalde günün
Eee ihtiyaçlarına karşılık geliyor Fakat bunlar kalıcı şeyler değil yani Türkiye
yüzyılı Dediğiniz zaman bu Türkiye'nin içinde bir Eee slogan mı yok yoksa
Türkiye'nin uluslararası ilişkilerinde eee vardığı bir noktayı veya varmaya
çalıştığı bir hedefi mi gösteriyor Bu Tartışmaya açık bir şey şimdi devletten
başlamamız lazım O yüzden sizin söylediğiniz şey de Eee Osmanlı
Devleti'nde özellikle Eee bu klasik dönemden itibaren cumhuriyete gelirken
Rumi tabir edilen bir grup var Rumi Romalı demek yani Rumi kelimesi Romalı
demek Eee bizim Osmanlı Devleti 3 romadır Eee doğru bakarsanız Eee bunu da Eee
işte Fatih Sultan Mehmet'le birlikte Kayzer unvanını kullanmalarında
görürsünüz rumiler devlet aklına sahip herhangi bir etnik gruba mensubiyet hissetmeyen dini
inanç bakımından da son derece Eee işte devletin ihtiyaçlarına uygun dini
kuralları icat etmek gibi Eee çok rahat e tepkiler veren bir grup
Eee böyle bir geleneği var bizim devletin ve bu işte
eee yani düşünün Osmanlı Devleti çok milletli bir imparatorluk ulus devletler
çağında böyle bir Devleti yaşatmanın imkansız Eee o yüzden Osmanlı Devleti'nde Osmanlı Devleti'ne ve
padişaha bağlılık yemini edenler Eee tutuyorlar yeni bir devlet kuruyorlar
bunu yıkıp eee ondan sonra devreye giren buna Eee Osmanlı'da şey de derlerdi
Cumhuriyet de intikal etti bu hikmeti hükümet bu tam karşılığı devlet aklı
denilen şey eee özellikle diplomaside Eee
Bürokraside Eee orduda bilhassa orduda var olan bir şeydir bu uluslararası
ilişkilerde kendini gösteren Eee devletin Eee işte cumhuriyetin
esasları dediğimiz ilk başta kurulmuş establishment yer alan prensiplere sahip
çıkan onları devam ettiren o kurucu irade dediğimiz Eee şeye sahip olan bir
aklın sağdan soldan böyle biraz Eee dağınık bir şekilde devrede olduğuna
dair bir inanç var herkeste yani son Rumi mi dediniz bunlara Rumi mi dediniz
böyle T Rumi Osmanlı döneminde Rumi deniyor Bunlar Osmanlı döneminde Rumi Rumi Roma isimleri var mı
Eee Vallahi işte şimdi Eee devletin sahipleri diyen var derin devlet lafı
çok oturmuyor buraya O daha çok illegal bir Devleti anlatmak için kullanılıyor
daha çok Eee kişilerden dönemden zamandan ihtiyaçlardan ayrı geçmişi ve
geleceğiyle bu devletin çıkarlarını Ali çıkarlarını bunlara her zaman Ali
menfaatler denir Ali menfaatlerini düşünen bu konuda yürüten insanlara
deniyor bu eee bu eee bazen bir düşünce oluyor
bazen doğrudan doğruya bir aktör oluyor bir kişi oluyor fakat yani o gazete köşe
yazılarında yorumlarında kitaplarda falan da görebilirsiniz bunu tarihçiler de e siyasal analistler de bu son derece
doğal bir şey yani bu Amerika'da da vardır İngiltere'de de vardır Eee büyük
sermaye kendini ülkenin çık larıyla özdeşleştiği için onlarda da vardır Bu
çok üzerinde duracak yani böyle çok e konspirasyon teorilere
Eee mesnet teşkil edecek bir şey değil Eee fakat bizde sorun şu
Eee devleti ele geçirenler Yani devlet iktidarın Bu bir kurum devlet dediğimiz
bir kurum Eee egemenlik hakkını kullanan o ülkenin egemenlik hakkını yürütme
yasama yargı gibi haklar kullanan kuruma diyoruz devlet yani Analitik bir şekilde
bakarsanız mesele biraz daha anlaşılır ve basit hale geliyor Bunu
kullananlar kendi iktidarlarını kendi pozisyonlarını takviye etmek tesviye
etmek için Eee Biz devletiz demeye başlıyorlar yani eee iktidar ile kurulu
iktidar ile Eee Geçmişten geleceğe Bu ülkenin milletin iradesini ve çıkarlarını temsil
eden Eee devlet birbirinden farklı şeyler şimdi bizde Eee mülk kelimesi kullan kullanılırdı
Eskiden mesela mülk Eee ta ibrani Tanrısı var Eee insanların Kurban
edildiği molok diye bir ibrani Tan Tanrısı var ondan Geliyor moltan geliyor
Eee yani batılılar bunu gene Yahudi Eee literatüründen alıp levian diyorlar e
Thomas hsun meşhur kitabı eee bir canavar şeklinde hep Tahayyül edilir
yani canavar şeklinde Tahayyül edilmesi biraz dışta tutulması biraz mesafeli
durulması Aslında kullandığı Yetkilerin Eee sahip olduğu Yetkilerin gücün
insanlar aleyhine kullanılma potansiyelinden kaynaklanıyor Eee o yüzden Eee devletle ilgili
konuşurken her zaman eleştirel bakılır Devlet iktidarının sınırlandırılması
dengelenmesi anayasal düzenler le Eee bunun bir Zap dur rapt altına alınması Eee o iktidarı ele geçirenlerin keyfince
kullanmalarının engellenmesi Eee bu tür şeyler devreye girer şimdi bizim
milliyetçilik ve muhafazakarlığın içine devlet kaçınca Eee bu sefer
Eee dengelenme denetlenemez frenlenir iktidar Eee
iktidarın şeyini temsil ediyor Duygu durumunu temsil ediyor diyor Eee Mümtazer Bey bir ara soru sorayım tamam
yani islamcılar eee iktidara çok uzaktı ikinci sınıf vatandaşlı Devleti çok
istiyorlardı Hani burada devletin içine kaçmasını makul karşılayabilirim ben
yani anlayabilirim ama milliyetçiler zaten devletin kendisi değiller miydi yani hiç yok ha değillerdi değillerdi
değillerdi bakın on onu bir şey yaparsak onu da en azından anlaşılır hale getirirsek eee E yani Türkiye çok hızlı
değişiyor bazı şeyler hemen unutuluyor 28 Şubat sürecinde hazırlanan milli
askeri stratejik Konsept Mask veya kırmızı kitapta Ülkücüler Eee terör
grubu olarak nitelendiriliyor Mesela bugün tam tersine Eee
meşruiyetini iyice genişletmiş devlet katında da
benimsetmek doğal kabul edilen bir şey bu bahsettiğim 20 yıl öncesinin şeyi yani 20 23 24 yıl önce kırmızı kitapta
Ülkücüler illegal örgütler ve şey olarak Devlet Düşmanı merkezler olarak kabul
ediliyordu Mesela bu unutuldu bunlar yani Tolga Bey bir duygu durumu dememin
sebebi bu Bunlar çok kolay değişiyor Muhtemelen bu iktidar değiştiği zaman da
bizim milliyetçilik muhafazakarlık algısı da değişecek
Eee devletle ilgili Eee çok bilinmez devlet kavramı şeydir Arapça bir kavram
Yani biz de Araplardan aldık bu kavramı kullanıyoruz devlet
Eee yani etimolojik olarak bu tür şeylere çok fazla girmek istemiyorum şeyiniz
Eee konuyu dağıtmamak için Eee dolaşık duran bir şeydir devlet
müdevver kelimesi tedavül kelimesi de devletle aynı kökten gelir Eee yani sabit bir şey değildir ve
Devlet Kuşu bu mutluluk kuşudur Saadet kuşudur birinin başına konar ve devletin
sahibi olur bütün tarih boyunca da böyle olmuştur şimdi Eee yani bir kuş gibi
dolaşan ortada dolaşan birilerinin başına konan bir şeyden bahsediyoruz Eee eee Türkiye'de her şey bakın Eee 28
Şubat döneminin şeyini düşünün devletini düşünün laiklik işte eee toplumun
muhafazakar değerlerine doğrudan doğruya şeriate dine karşı değil muhafazakar
değerlere açılmış bir savaş vardı şeyde 28 Şubat sürecinde ve 28 Şubat sürecinin
dünyasında Eee Bugün size son derece normal gelen
doğal gelen şeylerin tam tersi vardı bu şunu gösteriyor yani devletin
kendisi bağımsız bir varlık olarak kendi aklını kendi çıkarlarını kendi ideolojisini kendi sistematiğini
sürdüremiyoruz Eee 28 Şubat'ın yargısıyla bugünün yargısı yani birçok
alanda üniversite eriy le Eee medyasıyla birçok şeyi karşılaştırabilirsiniz buradan şu sonucu çıkartmak lazım
Bugünkü Eee kurulu iktidar yapısı da Kalıcı değil ve Eee yani bizim gibi Eee bu işi
anlamaya çalışanlara düşen de bunun nasıl evrilecek yakalamak
Eee Evet Eee şu görülüyor yalnız Yani bu
programda galiba konuşma gereken ana başlık o Eee milliyetçilik Eee Türkiye'de Eee
bütün cumhuriyet tarihi Eee boyunca olmadığı kadar revaç bulan taraftar
bulan yayılan kökleş bir ideolojiye dönüştü Fakat bunun ne kadar homojen bir
fikir Eee siyasi çizgi siyasi gelenek olduğu tartışa götürür İşte en son kme
ideolojisine dönüştü diyorsunuz Siz bir yerde Hayır duygu durumu Yani ideoloji tabirini kasıtlı olarak kullanmıyorum
Çünkü Türkiye'de milliyetçi Eee işte % 26 civarında oy aldı milliyetçi partiler
eee şey Mayıs ayında yapılan seçimde % 26 çok büyük bir oy oranı Eee ama
bunları parça parça karşıya getirdiğiniz zaman bir ideolojik ortaklık bile bulamazsınız yani Suriyeli mültecilere
Afgan mültecilere düşmanlık üzerine kurulu bir milliyetçilik de milliyetçilik olarak kabul ediliyor
futbol maçlarında ortaya çıkan işte Türk bayrağını alıp ortalıkta koşanlar da
kendilerini milliyetçi olarak tarif ediyor bugün Cumhuriyet Halk Partisi de
Eee geleneğine aykırı olmasına rağmen kendine milliyetçi bir parti olarak
takdim etmeye çalışıyor Eee yani ortak payda dediğimiz o milliyetçi ideolojide var olan ortak
payda ortadan kalkıyor Tehlikeli olan sadece şu içine devlet kaçınca ortaya Faşizm çıkar
Eee şeyin Eee Alman nasyonalizm İtalyan e
faşizminin ortak paydası şeydir Devlet üzerinden Eee fetiş leştir miş
putlaştırılmış Bir Eee millet fikridir Milliyet fikridir Eee Tehlikeli olan da
odur Eee ama Eee işte eee bir etnosentrizm yani eee kendi
halkını kendi etnik kimliğini yücelten ve herkesi de onun aşağısında gören eee
bir etnosentrizm dönüştüğü zaman tehlikelidir Eee Türkiye'de Eee bu şekilde belirli
kalıplara dökeceğim Eee
katılaştırıcı diyorum buna Duygu durumları hep geçici olur Bunların içinde Eee işte psikiyatristlerin dediği
gibi nevrastenik şeyler de olur E çok kullanışlı bir şey Mümtaz abi Kesinlikle
öyle çok kullanışlı yani eee herkes için yani toplumu Eee toplumu Manipüle etmek seferber
etmek konusunda milliyetçilik kadar Dünyanın her yerinde böyle milliyetçilik kadar kullanışlı eee bir şey yok E bir
fikir bir manivela yok manivela olarak bakabilirsiniz buna şimdi temel şey de şu
Eee yani bu bunu bir ölçü olarak kabul edebilirsiniz milliyetçilikle
vatanseverlik arasında bir ayrım yapılır Eee klasik tasnifler milliyetçiliği Eee başkalarına
düşmanlık göstermek başkalarından nefret etmek olarak vatanseverliği de kendi
milletini kendi vatanını sevmek olarak tarif ediyor Fransızlar Eee Fransız
patriyot izmiy le Eee milliyetçiliği mukayese ederken eee bir
etnosentrizm başkalarına başkalarından nefret etmeye Eee Devleti Eee fetiş
leştir putlaştırılan kaldıran bir Faşizme
dönüşme riski her zaman var Eee bu dediğiniz gibi şeye de müsait maniv
olarak toplumu eee manif etmeye de çok müsait bir ideoloji Eee ve Eee sürekli
düşman yaratarak yapıyorsunuz bunu mutlaka bir düşmanınızın olması gerekiyor ve bu düşmanlarla yatıp
kalkmak da hastalıklı bir durum tabii hocam Eee şöyle bir soruyla biraz meseleyi
açalım isterim Eee eee iki Eee bölümde sorayım size Eee birincisi çok net ve
basit milliyetçilik ve muhafazakarlık ya da İslamcılık diyelim muhafazakarlık
yerine islamcılığı koyalım Eee Bunlar nasıl yan yana gelebildi
Çünkü biraz önce siz de belirttiniz Örneğin ben hatırlarım Eee daha öncesinde Ülkücüler mesela İslamcı olan
gençlere yeşil komünist derlerdi Yani bu kadar net bir uçurum vardı Arada ama
bugün mesela bakıyoruz ki çok rahatlıkla yan yana Eee belirli bir Eee odakta
yürünebilir E bunu çok net görüyoruz birinci aşamadaki sorun bu
olsun bu iki kavram nasıl yan yana geldi İkincisi de
Eee Türkiye'de yeni bir rejimi artık idrak ediyoruz Muhtemelen bu yeni
rejimin oturması için de seçimlerden sonra E bir anayasa meselesi de gündeme gelecek gibi gözüküyor e yeni bir
anayasa Çünkü mevcut anayasayı şu anki yönetim ya da da iktidar tanımadığını
her haliyle ifade ediyor belirtiyor gösteriyor Eee Örneğin 30'lu yıllarda da
yine böyle bir geçiş dönemiydi yeni bir rejim vardı ve yapılan e bazı uygulamaları bugün çok jakoben olarak
adlandırıyoruz o uygulamalara baktığımız zaman ama bugün mesela Eee aynı şekilde
yeni bir rejimin oturduğunu gördüğümüz halde Eee bu kadar jaken olmamakla
birlikte daha esnek ama çok daha net ve hayatımıza işleyen bir tavır görüyoruz
aynı zamanda yeni bir Eee elit bir sınıfın ya da daha zengin bir grubun oluşturulduğunu görüyoruz Bu süreç
içerisinde milliyetçi ve muhafazakar kodlar nasıl evrildi nasıl bugüne geldi
böyle bir soru sormuş olayım Şimdi ikinci sorudan Eee Baha Bey isterseniz
başlayalım çünkü birinciyi de Eee büyük ölçüde aydınlatıyor ikinci sorunun cevabı Eee bugün iktidar yapısını
Türkiye'de 20 yıldır devam eden iktidar yapısını Eee Bir siyasal İslam projesinin
iktidara gelmesi ve iktidarda ölmesi yok olması kaybolması olarak görebiliriz H
Çünkü İslamcılık özü itibariyle muhalif bir ideolojiyi bunun Eee iktidar
ideolojisine dönüşecek araçları da yoktu Yani siz Eee küfür Devleti devlete küfür
Devleti derken Burası Darül harb derken Eee işte laik düzeni küfür düz düzeni olarak
nitelendirir negatif şeylerle Eee kendinizi takdim ederken Eee Türkiye'de
özellikle işte şehirleşme Eee toplumdaki Eee orta sınıfın yok olması yoksullaşma
bu tür şeylere karşılık gelerek Eee işte toplumdaki Dindar hane eğilimlerle de
bunu buluşturarak bundan bir Eee siyasi parti çıkartmanız organize etmeniz
toplumsal taban sağlamanız ve iktidar gelmeniz normaldi ama oturup Bu negatif
şeyleri iktidara taşıdığınız zaman bir de kucağınızda devlet var veya Üzerinizde giydiğiniz kıyafet devlet var
Onu da yönetmeniz Eee sevk ve idare etmeniz lazım Eee bu sefer şey çöküyor
Eee islamcılığın size vereceği hiçbir Araç yok Devleti yönetmek için Devleti
devlete çeki düzen vermek için ve şeyi boşaltıyoruz ideolojik bagajı
boşalıyorsa ve bu sefer Eee biraz da doğal bir
şekilde milliyetçiliğe kayıyorsa bu yani şöyle düşünün
Eee çok ilginç AK Parti iktidarının başından itibaren ellerindeki Medya
gücüyle Eee Propaganda gücüyle ürettikleri şey İslamcılık olmadı milliyetçilik oldu
Evet televizyon televizyonlardaki dizilere bakın mesela İsam bir şey
çıkmıyor onlardan doğrudan doğruya Hatta Siz münzer Bey hatta bir ara dediniz bir yerde yani muhalefete bakarsak dört
parti var Hani bunlar daha İslamcı e tanımlanabilir şeyler ve muhalefetten
yani iktidar iktidara nasıl İslamcı denilebilir şeklinde bir soru da söylüyorsunuz ve ciddi anlamda da şey
var yani İslamcı bir entelektüel muhalefet de var Türkiye'de yani eee Evet yani Baha Bey'in sorusunda olmayan
bir şeydi o ciddi manada ayrışmış artık o başlangıçtaki siyasal İslamcı projeye
hala sadakatle bağlı olan onun eee bir ideal veya bir Ütopya olarak
mevcudiyetine bel bağlamış olanlar ayrışıyor ve Eee bu iktidara da
Eee yani bana sorarsanız Eee makyavel'in 15 yüzyılda yazdığı kitapta hangi
esaslar varsa onları uygulayan bir iktidar yapısı çıkıyor doğal olanı da bu iktidarda aktır şeyin problemi
iktidarların problemi Ya böyle bir şey mecbur diyorsunuz yani yapmaya Yani bunun ideolojiyle falan ilgisi yok yani
eee yani siyasetin tek şeyi vardır ölçüsü vardır başarı sizi başarıya
götürecek olan şey İslamcılık değildi Çünkü oradan bir şeyler çıkartıp Eee
uygulamaya kalktığınız zaman toplumu bölersiniz Devleti Dağıtırsın uluslararası
ilişkilerinizi Baltalar Tonlarca arıza çıkar ona uygun şeyler geliştirildi
zaten İslamcılık yerine muhafazakarlık tabiri kullanıldı batıda bize moderate
İzam diye Eee biraz yumuşattı yumuşatarak benimsedi aldı ya da AK
Parti'nin ilk yıllarında muhafazakar demokratlık gibi bir kavram uyduruldu falan kavram vardı o da Baha Bey yani O
hatırlatmanın çok doğru yok şimdi tedavülde yok yani AK Parti iktidarını
doğuran ideolojiyi muhafazakar demokrasi bugün yok ve o muhafazakar demokrasinin
içinde hakikaten gerçekten de demokratik idealler vardı ilkeler vardı işte Sivil
Toplum çoğulcu toplum Eee iktidarın denetlenmesi devlet
iktidarının sınırlandırılması gibi hukuk devleti Eee hukuk devleti gibi işte
adaletin tesisi gibi eee şeyi belirleyen Eee doğrudan doğruya Eee muhafazakar
ideol belirleyen temel ilkeler bunlardı şimdi iktidarda kaldığınız zaman Yani
bütün tarih boyunca da böyle Eee din ideoloji ideolojik araçların
tamamı iktidarda kalmanın veya sürdürmenin aracına dönüşüyor
Eee bütün tarih boyunca da böyle bunun istisnası yok o yüzden şeyde Siyasette ölçü Her zaman makyavel'in ilkeleridir
başarıdır tek ölçü Eee Hatta makyavel der ki Eee yani ahlak Siyasette ahlak
yoktur mesela makyavel'in sözü bu eee ahlaklı bir hayat yaşamak istiyorsanız gidin köyünüzde inzivaya çekilin der şey
makyavel bu şey var Meşrutiyet döneminde Hürriyet ve itilaf Lütfü Fikri Bey Onun
bir sloganı var Ben bunu söylediğim zaman insanlar gülüyor daima muhalefet diye bu herhalde çok ütopik bir şey yani
böyle bir yani hiç iktidara gelmeyi
programınız almamak gibi e Sürekli orada kalmak gibi bir idari yansıtıyor ifade
ediyor evet yani eee şaşırtıcı değil sonuç itibariyle
yani realist bir şekilde değerlendirirseniz gerçekçi bir şekilde değerlendirirseniz şaşırtıcı bir şey
değil ideolojiniz boşaltı musunuz iktidar olmanın gerekleri icapları
nelerse ona uygun davranıyorsunuz ve ortaya Eee sürdüğüne göre de başarılı
bir iktidar çıkıyor ve bu e Değişim dönüşüm içinde de İslamcılık size
uymuyor eee şey uyuyor milliyetçilik uyuyor milliyetçilik Çünkü Sahip
olduğunuz devletin ulusal karakterine uyuyor Ulus devlet özelliklerine uyuyor ve
Eee bu yorum için erken mi bilmiyorum ama benzer yorumları yapanlar da var
Eee dini değerler dindarlık Eee işte bir siyasal İslam projesini
besleyen Eee İslami idealler Bunlar Eee Türkiye'de çok geriledi bu iktidar
sayesinde yani İslami tezlerle ortaya çıkıp Eee sonra makyavelist bir tablo
çizen iktidarın Eee en eee erken sonuçlarından biri Türkiye'de
dindarlığın Eee gerilemesi dini değerlerin dini değerler
etrafındaki eee uzlaş Eee eee onlar onları yaşatma iradesinin
kararlılığının Bütün bunların gerilemesi oldu Eee Türkiye Hatta Yani o kadar
haklı bir yerden bakıyorsunuz ki cemaatleri bile mesela dünyevileşir Yani bir nevi
sekülerleştirme Bakış ya da dünyevi olmayan bir şey kalmadı gibi bir şey
yani Baha Bey bu noktada çok önemli bir nokta Hayati bir nokta Çünkü Eee laiklik tartışılırken Türkiye'de hep
işte laik dünya görüşünü benimseyenler le dini değerleri benimseyenler arasındaki çatışmalar nasıl çözülür diye
bakıyordu herkes fakat biz bugün şunu tecrübe ettik farklı dini yorumlara
bağlı olanlar farklı dini prensipleri takip edenler Dini farklı şekilde
yorumlayanlar arasındaki çatışmalar nasıl önlenecek güç savaşları nasıl
engellenecek bir tarikatın bir cemaatin hakimiyeti Ötekiler ezmesi nasıl
engellenecek Mesela laikliğe şimdi Bu çerçevede bakıyoruz artık Eee darmadağan
etti şeyi Eee Eskiden Eee eski Rejimde ansiyen
rejimdeki o laiklik İslamcılık tartışmalarını darmadağan etti şimdi
Eee şeyde bile yani Dindar kesimde bile ciddi manada laikliği anlayanlar için
bir şey var Eee eğilim var bunu çok kuvvetli bir
şekilde ifade ediyorlar Çünkü farklı dini yorumları bir arada yaşatacak dini
bir yorum üretemiyor musunuz Bakın bu Paradoks Evet Eee farklı dini yorumlar
bir arada barış içinde yaşayacak bunu üretece bir dini yorum Eee ve Eee
dünyadaki gelişmeler de işte bir Arap baharı şeklinde tecelli eden Eee dindarlığın demokratik özüyle
alakalı Eee gelişmeler de Eee şeye uğradı başarısızlığa uğradı ve
karşımızda bir Afganistan örneği var bir Taliban Eee örneği var şimdi oturup
Taliban'ın Eee Afganistan'da kurduğu ve sürdürdüğü sürdürdüğü rejim
Eee dini açıdan Eee Tasvip edilir eee benimsenir bir rejim olduğunu
söyleyemiyor kimse Yani bir peştun milliyetçiliğinin Afganistan geleneklerine göre üretilmiş
bir şeriat anlayışının Eee şeriatın kendisi mi olduğu yoksa başka bir şey mi
olduğu konusunda Eee çok canlı bir şey yaratıyor Paradoks
yaratıyor çelişki yaratıyor Siz ona baktığınız zaman herhalde bu işin çözümü için laiklikten başka çare yok diye
düşünmeye başlıyorsunuz Eee ve bu bakın Eee iktidar Eee işte her
yere Cami inşa etti çok güzel camiler yaptılar çok büyük camiler yaptılar
Eee işte eee ortaöğretimi neredeyse tamamıyla İmam ha
tipleştirme her ilde bir ilahiyat fakültesi var E din eğitime özel olarak
önem verdiler ve dine çok büyük yatırım yapıldı Diyanet İşleri Başkan başkanlı
personelinin Eee özlük hakları düzeltildi sayıları arttırıldı
itibarları Eee diğer devlet memurlarına göre epeyce yükseltildi sonuç sonuç
Türkiye'de dindarlık geriledi yani namaz kılanların oranı oruç tutanların oranı başını örten genç
kızların oranı azaldı Şimdi bunu bunu açıklayacak
eee bunu açıklamanın galiba tek yolu da gene işte bu siyasal İslam'la devlet
iktidarı sahibi olmak buradan Eee devlet iktidarı sayesinde elde ettiğiniz
Eee pozisyonun işte devletin ekonomik imkanlarını kullanmanın ekonomik
araçlarını seferber etmenin getirdiği avantajlarla Eee sınıf atlamanın
statünüzü Eee geliştirmeniz Bunlar arasındaki bağlantının ciddi ciddi
analiz edilmesi lazım hocam Peki şunu söyleyebilir miyiz bu bütün bu süreç
içerisinde Eee Kemalist paradigmanın iflas ettiğini e söyleyebilir miyiz
ifade edebilir miyiz Çünkü bu Paradigma hem milliyetçiler hem de islamcılarla
sorunluydu çatışma halindeydi yani eee fakat geldiğimiz nokta itibariyla
görüyoruz ki aslında Kemalist Paradigma son derece kristalleşmiş ve Eee
donuklaşmak adına eee hiçbir karşılığı olmayan hayata tekabül etmeyen bir
Paradigma olarak İflas etmiş gözüküyor çünkü bugün Hem milliyetçi unsurlar hem Eee dindarlar
eee Tabiri caizse Eee tepiniyor yani bu Paradigma üzerinde Yani Kemalist tabiri
doğru bir tabir mi bilmiyorum ama Eee sizin söylediğiniz şeyin tam tersini düşünüyorum ben Baha Bey H
Eee cumhuriyetin kuruluşunda Eee kurucu irade dediğimiz sergilenen bir irade var
bu bir ulus devlet olarak Türkiye Cumhuriyeti Devleti'nin temel parametrelerini belirlemişler temel
dengelerini oluşturmuşlar temel kurumlarını oluşturmuşlar Eee Eğer kastettiğiniz 27 Mayıs
darbesinden sonra ortaya çıkan Atatürkçülük ise o farklı o tamamıyla
farklı ama Cumhuriyeti Kuran iradenin oluşturduğu dengeler var Türkiye
Cumhuriyeti Devleti'nin Eee işte sağlıklı Ne bileyim işleyen Eee kendini
idame ettiren Eee varlığını koruyan Eee üstlendiği görevleri yerine getirmesini
sağlayan dengeler Bunlar mesela bunlardan şeyi örnek vereyim Diyanet İşleri Başkanlığının kuruluşunu
Eee bizim o Kemalist Eee Paradigma dediğimiz şeyin çok dışında bir şey bu
şimdi 1924 24 yılında 429 sayılı kanun Diyanet İşleri riyaseti kuruluş kanunu
çok önemli bir örnek olduğu için size bunu anlatmak Eee ihtiyacı içindeyim şimdi Eee şöyle diyor kanunu kurarken bu
aslında cumhuriyetin felsefesini de yansıtan bir şey diyor ki Eee İslamiyet dini mübini İslam'ın Bir
de överek söylüyor İslamiyet'in muamelata dair hükümleri Türkiye Büyük Millet Meclisinin uhdesindedir diyor
Bunun dışında itikad ve ibadat ilgili hükümlere ise Diyanet İşleri Başkanlığı
bakar diyor bir de dini müesseselerin yönetilmesine Şimdi şöyle bir formül
getiriyor Eee ben Müslümanım ve dini kurallara uygun dinim
Ne emrediyorsa o şekilde yaşamak istiyorum Bana diyor ki kanun Eğer böyle
yaşamak istiyorsan Eee ben senin uyman gereken muamelat
hükümlerini Türkiye Büyük Millet Meclisi tarafından yapacağım Bu da zaten şeyde İslamiyette icmi Ümmet dedik şeyin 3üncü
kaynağıdır edille-i Erbaa'nın 3üncü kaynağıdır Ben Türkiye Büyük Millet Meclisi'ne Bunu yaptıracağım
eee şeyi de ibadetle ve Eee İnançla ilgili konuları da Diyanet İşleri
reisliğine bırakıyorum diyor şimdi Türkiye Cumhuriyeti Devleti'nin belki de en stratejik kurumudur bu kurucu irade
dediğimiz şey Diyanet Diyanet Diyanet İşleri Başkanlığı öyle bir yere yerleştiriyor ki sonrasında biliyorsunuz
siyasi partiler kanununda da diyanetin kaldırılmasını istemek partinin kapatılması sebebiydi O kadar önem
önemsenmiştir Başkanlığı cumhurbaşkanlığından sonra mı geliyordu şeym mi ba başbakanlığa bağlıydı Eee
Aslında Protokolü de biraz geri bir yer veriyorlar müsteşarlık düzeyinde bir yer veriyorlar fakat eee şey ş olarak Eee
yani devletin kimyasında çok önemli bir yer dinle ilgili problemini bu şekilde
çözmüş muamelatla ilgili Medeni hukukla ilgili Eee kuralları Türkiye Büyük
Millet Meclisi çıkardığı kanunlarla düzenlediği zaman ben buna Dini kurallar olarak Eee hem itaat etmek hem de zaten
vatandaş olarak uymak zorundayım yaklaşımları böyle bir yaklaşım şimdi Eee Kemalist proje diye Eee bahsedilen
şey eğer 1930'lu yıllardaki Eee İşte o özellikle faşist İtalya'dan ve
Almanya'dan alınan Eee Recep pek özür dilerim Diyanet İşleri Başkanlığı 12
sıraya yükselmiş 40 sıra yükselmiş Genelkurmay Başkanlığının önüne geçmiş son düzenlemeyle protokolde değil mi
devlet protokol protokol 12 sıraya yükselmiş 40 sırada Eee şöyle bir soru
sormak lazım Eskiden vatandaşların diyanete Eee itibarı ne kadar gerilemiş
Eee onu da sormak lazım Çünkü bunda çok müthiş bir gerileme var yani ben bunu
cami imamlarında müezzinlerinden ve şeyde de görüyorum Eee yani din adına fetva veren hüküm
verenlere yönelik ilgide de müşahede ediyorum bu konuda araştırmalar da yapılıyor Eee protokol de arttırıyordu
ama fiili olarak itibarı geriliyor eskisi gibi değil Eee Evet Eee
yani bu kurucu irade Bu tür dengeler üzerine Eee kurmuş temel Ulus devlettir
diyor bunu diyor Ben diyor dini Daha sonra da ezanı Kur'an'ı türkçeleştir
bunu millileştirme denemesi yapmış fakat başaramamış ama bir şekilde
Eee bulduğu formülle dinle bir uzlaşma içine girmiş Tıpkı Osmanlı Devleti'ndeki
şey islamlık kurumu gibi almış onu kendi içinde meclis etmiş ona bir mevki makam
tanımış Eee bu yapının Aslında Eee ben Eee
oldukça sağlam bir şekilde devam ettiğini düşünüyorum yani eee Son 20
yılda Eee bu çizginin dışına çıkmayı ve dini kuralları dini esasları Eee toplum
için belirleyici bir duruma getirme konusunda en küçük bir ilerleme olmadı
tam tersine Eee işte eee bu Merkez Bankası faizi arttırırken Nas var Nas
laflarıyla Aslında dini referanslar da Eee tahfif edildi yani küçümsendiğini
siyasete alet ederseniz Eee dini sembolleri dinen kutsal sayılan şeyleri
siyasete Eee alet ederseniz onların itibarıyla oynarsınız Hıı Hı hı Eee
geçici olarak size bir şeyler kazandırır fakat Eee Dindar insanın dünyasında Eee
hayal dünyasında ruh dünyasında Eee karşılığı olmaz Eee Türkiye böyle
bir tecrübeyi yaşadı E bu anlamda bunu da gene şey sorayım münzer Bey bu
sıra şey bu anayasa tartışmalarıyla ilgili gündeme geldi Eee Teşkilatı Esasiye 21 Anayasası
diyebileceğimiz yeni yazılacak olan anayasanın çok kısa olacağı ve 21 anayasasını Hani merkeze
alacağı söyleniyor şimdi 21 Anayasası Bildiğim kadarıyla islamcılar
için bir kutsal Metin gibi neredeyse Yani hep 21 anayasasına şey
var Atıf vardır çünkü ondan ziyade bir toplumsal ondan ziyade bir toplumsal
mutabakatı temsil ediyor Bir de tabii 1 maddesi Hani Devletin dini din islamdır
şeyinin birinci madde olarak geçmesi ve dolayısıyla kimliğini Çok belirgin hale
getirmesi şimdi böyle bir şeye ihtimal veriyor musunuz diye sormam lazım Çünkü daha bu anayasa çalışması başlamadı ama
Bu tartışmalar da sanki böyle bir Zihni şey de var yani burada bir çeliş varin
bu anayasayla ilgili bir çalışması da var yani iktidara verdiği maddelik bir
önerisi de var bu anayasayla ilgili yani Mesela Devlet Bahçeli böyle bir anayasa
çalışmasına nasıl bakar Çünkü anayasanın sahibi Tabiri caizse Devlet Bahçeli yani
Erdoğan vazgeçer ama Bahçeli herhalde vazgeçmez diye düşünüyorum İki madde Çünkü Bahçeli için çok önemli bir
Cumhurbaşkanlığı meselesi Erdoğan 50+ biren rahatsız oldu hani acaba dedi
Bahçeli dedi ki devlete Muhtar seçmiyoruz bir daha Sayın Erdoğan bunun lafını bile etmedi Bir de bu anayasa
meselesi şimdi Tolga Bey E ben anayasa gündemini ve tartışmalarını ciddiye
almıyorum Eee yani hiçbir şekilde bunun fiili bir karşılığı yok yeni anayasa teşebbüsünün
de Eee anayasayla ilgili tartışmaların da Eee ve hazırlanan anayasa metinlerinin
de bir anlamı yok bir karşılığı yok sebebi şu anayasa niye var diye sormak
lazım Anayasa ne için yapılır anayasa devletin sahip olduğu egemenlik güçleri
arasında dengeler kurarak fren mekanizmaları öngörerek o gücün Eee
vatandaşın aleyhinde kullanılmasını kötüye kullanılmasını iktidar sahipleri tarafından suistimal edilmesini
engellemek için yapılır anayasacılığın tarihi de böyledir zaten çok eski değildir Yani 200 yıllık 250 yıllık bir
tarihi var anayasacılığın iktidar sahiplerinin gücünü frenlemek dengelemek
için başlamıştır anayasacılık şimdi bir anayasa yapacaksanız Öncelikle şu soruyu
sormanız lazım Eee yargının bağımsızlığını nasıl sağlarsınız Çünkü
Eee sandıktan çıkan bir iktidara yürütmeyi veriyorsunuz yasamayı da veriyorsunuz ama yargının bağımsız
olması lazım yargının yürütmeyi de yasamayı da denetlemesi lazım vatandaşın
en temel haklarının da kefili olması lazım onları koruması lazım şimdi eğer
Eee kuvvetler ayrılığı prensibine dair
Eee yargının bağımsızlığına dair bir öneriyle gelmiyorsan zaten bir anayasa
öneriniz yok demektir anayasanın ruhuna aykırı bu yani siz
Eee yürütmenin yetkisini biraz daha arttıracak bir anayasa teklifine
yasamanın Eee yürütmenin eline verilmesini daha da kuvvetlendirecek bir teklifi yeni anayasa tartışması diye
sunarsanız Eee yani buna oturup hep birlikte Gülmemiz gerekir kahkahalarla
Gülmemiz gerekir Yok böyle bir anayasacılık dünyanın hiçbir yerinde yok şeyin E bakın 1789 Fransız İhtilalinin o
meşhur Evrensel beyannamesinin 17 maddesi olması lazım diyor ki
Eee yargı bağımsız değilse bir ülkede anayasa yoktur diyor anayasa yoktur yani
anayasa diye bir bir şeyden bahsedemezsin şimdi soru şu mesela anayasa tartışması neden çıktı Can
Atalay kararına Anayasa mahkemesinin Can Atalay kararına eee şey
uymadı yargının diğer bölümü Eee Uy Detay 13 dairesi hocam Eee şimdi dediler
ki bu şeyi ikisi arasındaki ilişkiyi yeniden düzenleyelim o zaman soru şu
Anayasa mahkemesinin kararlarına uyulacak mı uyulmayan yapacağınız
anayasada bakın anayasadan bahsediyorsanız o anayasaya kefil olacak en stratejik kurum anayasa mahkemesidir
Çünkü anayasaya aykırılığı denetler Eee sonradan Temel hak ihlallerini de
Eee belirleme ve durdurma yetkisi verildi Anayasa mahkemesine şayet Siz
şeyin yetkisi yok mesela Anayasa mahkemesinin Anayasa Mahkemesi bir karar verdiği zaman yargının diğer
birimlerinin verdiği karar Yargı kararı olmuyor Eee yürütmenin baskısı altında veya
başka saiklerle verilmiş bir karar oluyor yargıda temel prensip şudur Eee
doğal yargıç kuralına göre hangi mahkeme hangi yargı birimi karar verdiyse odur
geçerli olan bir başka yargı birimi kalkıp onu etkisiz hale getirirse o zaman yargı
bağımsızlığı da yok demektir yani Neticede anayasa dediğimiz anayasa gündeminden bahsediyorsak kuvvetler
ayrılığı prensibi nasıl işleyecek yargının bağımsızlığı nasıl sağlanacak
yargının bağımsızlığının sağlanmasının yanında Eee yargı kararları Eee
tereddütsüz nasıl uygulanacak bunu nasıl düzenleyeceğiniz diye sormak lazım Yeni
anayasadan bahsedenlere Eğer bunlar yoksa zaten anayasadan bahsetmiyorsa kaldırın atın şu anda olduğu gibi yani
anayasa uygulanmıyor Eee anayasanın uygulanmadığı bir yerde Eee mevcut anayasa mevcut kuralların
uygulanmadığı bir yerde yeni anayasadan bahsetmek hakikaten toplumla dalga geçmek gibi bir
şey Evet bu şeyi ben soru var Tolga Ama özel
soruları burada hocamıza yöneltmeye alalım yani onları alırız birkaç şey soracağım mesela
Eee bazı çok orijinal güzel sorular var Onları alalım ama özel soruları
almayacağız burada çünkü değil burası Şimdi siz mesela diyorsunuz
milliyetçilik yangına benzinle gitmek gibidir mesela Kürtlere karşı Türk
milliyetçiliği yapmak millete ihanettir
milliyetçiliği yeniden tanımlıyorsunuz gibi geldi bana Mesela bu
cümleyle yani devletin devletin yeni bir tanıma ihtiyacı var herhalde yani
milliyetçiliği eee
ötekileştirmeden ülkücüsü milliyetçisi Mümtazer türköe Eee milliyetçiliği
tamamen reddetmiş gibi bir şeyi anlamıyorum ben herhalde ben yani Tolga Bey ben hala kendimi milliyetçi olarak
tanımlarım Eee yani bu bu ülkenin tarihine Eee milli Eee
eee bir millet olarak sahip olduğu değerlere bağlıyım yürekten bağlıyım E
ben zaten Oğuz Oğuz soyundan geliyorum yani kendi atalarımın bana bıraktığı
mirasa aykırı davranmam da mümkün değil ve bir imparatorluk varisiyim Eee hiçbir zaman devletsiz kalmadım
Eee ve Eee millet olarak gerçekten Eee tek tek
Eee sıralamak mümkün insanın Eee göğsünü gururla dolduran bir tarihe sahibim
gurur duyduğum bir tarihe sahibim bu Tarihin en önemli özelliği benim tarihimin en önemli özelliği Farklı
etnik gruplara farklı dillere farklı inançlara hoşgörüyle bakan ve bu Bu
sayede de çok kalıcı Eee istikrarlı bir devlet geleneği oluşturan bir millet
olma Yani ben bir imparatorluk varisiyim Eee 72,5 milleti bir arada yaşatmış bir
milletin Eee evladıyım Eee bunu zihnimde aklımda
Eee yaşatıyorum ve Eee yaşamasını savunuyorum Şimdi siz Türkiye'de Eee
Kürtleri dışarıda bırakan bir millet tasavvuru ile Eee Hatta Kürtleri dışarıda bırakmanın
ötesinde Kürtlere düşmanlık gösteren bir millet tasavvuru ile hareket ederseniz yola çıkarsanız o zaman
eee bir milliyetçinin yapm Gerektiği şekilde Eee Türkiye'nin bölünmesini Eee
devletin küçülmesini savunuyorsunuz demektir yapacağınız milliyetçilik
tanımının bu ülkede yaşayan her bireyi kapsaması lazım Eee size bir milliyetçilik tarifi
vereyim Aslında Türkiye Cumhuriyeti Devleti'nin kuruluşunda da bu tanım vardır milliyetçilik g Ziya Gökalp
referansı mı onu söyle Hayır Eee şeyin de Atatürk'ün de kullandığı E şey ern
Ran'ın referansı 1881'de verdiği bir konferans
var Bir Millet nedir kes Köse ün nasyon diye çok meşhur bir şeydir metindir o
Atatürk onu medeni bilgiler kitabında da kullanır Eee orada yapılan millet tanımı
en genel geçer millet tanımıdır millet Kader birliğidir bir millet Kader
birliğidir o ülkede yaşayan insanların eee geçmişte birlikte yaşamaları ve
gelecekte de birlikte yaşamak konusunda irade sergilemeleri yani başlarına bir şey
Güneydoğu'da Diyarbakır'da birinin başına bir şey geliyorsa benim de başıma geliyor demektir kader birliği de budur
Bu Kader birliğine uygun milliyetçilik tarifi dışında Eee geri kalan Eee
özellikle Türkiye'de Eee Duygu durumuna göre değişim gösteren Eee Faşizm türü
eee milliyetçilikle etnosentrizm başkalarına düşmanlık
üzerine kurulu milliyetçilik anlayışıyla Eee mutlaka Araya bir çizgi çekmek
gerekir Bir Mesafe koymak gerekir milliyetçilik Kader birliğidir kader birliği etmektir bu ülkede yaşayan
insanlarla Yani siz Kürtleri dahil etmediğiniz bir millet anlayışını bu
topraklarda Egemen kılmaya kalkarsanız bu ülkeyi bölersiniz bu ülkeyi bölen Siz olursunuz
yani Bunu ister istediğiniz kadar E ben
çoğunluğumuz bu sizin kendi milli varlığınıza da kendi devletinize de ihanettir
Eee benim temel şeyim Bu temel yaklaşımım bunu hiç değiştirmedim hiçbir zaman da değiştirmedim
eee bir kader birliği yani Çanakkale'de savaşırken Ben Kürtlerle beraber
savaştım Balkan savaşlarında geri çekilirken Kürtlerle beraber geri çekildim eee Eee Onlar da benim
yanımdaydı Biz Kurtuluş Savaşı'nda Eee yani bizim tarihimizin en zor dönemidir
Kurtuluş Savaşı Eee kabustur Kurtuluş Savaşı'nda
Eee kürkler bizimle beraber Eee direndiler şeye karşı
Eee sevri eee Kürtlerle beraber parçaladık yani şeyde Eee 9 İsyan var
kutuluş Savaşı boyunca Biz asıl cephe de bu isyanlarla uğraştı Kurtuluş
Savaşı'nda Eee Konya'da Kastamonu'da Düzce'de Eee bilirsiniz o isyanları Eee
bunların arasında Kürt isyanı yoktur İsyan edenler
Türkler Eee ben Kurtuluş Savaşı'nda savaşırken yani neyse oralara girmeyeyim benim
yaram Bunlar Çünkü tar tarihi olarak Eee Bir milletin en büyük yarasıdır o
Kurtuluş Savaşı bize çok şey öğretti ben bu milleti tek parça halinde
yaşatmak ve bu devleti de milletiyle ortaklaştırma zorundayım Yani bu ülkede
yaşayan insanlar devletinden razı olacak Devleti de onları bir arada yaşatacak
ikisinin karşılıklı yükümlülüğü bu Eee bunu yerine getirmek için de
Eee bölücü olmamak lazım yani çoğunluk bölücülüğü ile azınlık bölücülüğü
arasında hiçbir fark yok Siz mesela Erdoğan başbakanken
şey diyordu Biz milliyetçiliğin her türlüsünü ayaklar altına aldık ve siz bu
anlamda Ben bir milliyetçi olarak Hani tumu söylemek zorundayım ve buna
katılıyorum dediniz demiyoruz ha demiş miyim
demişsiniz bu tam olarak bu tam olarak Biraz önce anlattığım şey yani
ben bir tartışmaya girmiştim yıllar önce Eee Türkiye'yi Eee şeyler Kürtler değil Türkçüler
bölecek diye Türkçülük yapanlar bölecek diye böyle bir tartışmaya girmiştim bu
Türkiye'deki genel milliyetçi Eee eğilimle ilgili problemi de yansıtıyor Yani ben tekrarlıyorum vurguluyorum
Eee ben devlet bilincine sahibim Ben tarih bilincine sahibim milliyetçilik
tarih bilincidir benim yaşadığım ve yaşattığım tarih benim Egemen olduğum tarih benim hakim
konumda olduğum tarih farklılıkları bir arada yaşatma becerisiyle kendini
kanıtlamıştır kendini var etmiştir ve ben onu hala yaşatıyorum benim
milliyetçiliğimiz hızlandır alım Eee bahım biliyorum sorulara geçmek istiyorsun Ben de münzer yok hayır e
hocamız yorulur diye endişe ediyorum yoksa hayır hayır b abi yani bu eski
programlar gibi değil evde gayet güzel çayım yanında
Sizler de maşallah çok verimli bir şey yürütüyorsunuz tartışma yürütüyorsunuz
Estağfurullah hocam sigara bilirsiniz yani eğer kullanıyorsanız Burası YouTube rahat olun yani e Mümtazer türköe Mesela
daha önce de böyle mi düşünüyordu Hani izleyicilerimiz için Soralım yoksa e
affedin beni Eee devletin eee şey siz biliyor yeni çıktınız
şeyden Eee biraz sizi dinlendirdim ve orada orada düşünceleriniz mi değişti çünkü
bunlar sorulabilir soruluyordu da Eee böyle miydi hep hep böyle mi
düşünüyordun Yani ben Tolga Bey sorunuza çok genel bir cevap vereyim Eee yani
insanın felsefi anlamda Eee düşünce tarihi anlamında ideolojik prensipler
anlamında düşünceleri değişebilir Eee Fakat ben bu ülkeye aidim ve her şeyimi
bu ülkeye borçluyum bu millete borçluyum Eee bunun dışında hiçbir şey
düşünmem zaman zaman konjonktüre göre dengelere göre Eee bu söylediğim temel esas
çerçevesinde farklı şeyler Doğru olabilir o konuda Eee işte çok aykırı şeyler de
söyleyebilirsiniz bazen eee bir genel akım vardır zararlıdır görüyorsunuz bunu Eee Türkiye'yi çok
yanlış bir yere götürdüğünü zarar verecek görüyorsunuz aykırı bir şey söylersiniz aykırı şeyi söylemek de
sizin göreviniz deir Eee yani madem Eee konuşuyorsunuz bir şey söyleyeceksiniz
Eee insanları sarsacak kendini kendine getirecek bir şeyler de söylemeniz gerekir Fakat Eee ben bu ülkeye aitim
yani bana ideolojik bir değer ideolojik bir tavır olarak soruyorsanız ve bu ülkeye borçluyum her şeyimi
Eee tarih bilincim çok kuvvetli eee yani bir de tarihi bilerek söylüyorum bunu
Eee ve kendimi Orta Asya'dan Buraya gelen atalarım la Eee Göçebe Eee
atalarım la Eee aynı ruh hali içinde buluyorum Eee ve işte bir 600 yıllık
Osmanlı İmparatorluğu dünyada Egemen olmuş Eee farklı milletleri farklı dinleri bir
arada yaşatmış barış içinde bir arada yaşatmış ve bu konuda hala aşılamam bir eee Emsal oluşturmuş bir devletin
varisiyim bu konularda Benimle kimse rekabet edemez bu anlamda Ama
oturup Eee işte milliyetçiliğin faşist yorumuyla milliyetçiliğin liberal
yorumuyla milliyetçiliğin muhafazakar yorumu da var bunlarla ilgili yani çok
uzun tartışmalar yürütülebilir bu beni çok fazla önemsemiyor sorulara geç önce Son soru
sorayım ondan sonra geçelim olur mu Ben soruların dışında bir şey sorabilir miyim Hoca Tamam buy
Buyur münzer hocam biz böyle çok uğraşıyoruz birbirimizle Kusura bakmayın yani eee Estağfurullah B Bey Eee hocam
Eee Türkiye'deki mevcut rejimin Eee milliyetçi muhafazakar olarak
tanımladı iktidar değişirse bu milliyetçi muhafazakar kavrayış ya da uygulama ya da anlayış değişir mi Yani
şöyle Bu sorunuzun da kesin bir cevabı var Eee iktidarlar toplumdan gelen
eğilimlere göre biçimleniyor biçimlendi güç geçirdiği zaman kendi
istekleri iradeleri Eee istikametinde de ellerindeki araçları medyayı devletin Propaganda imkanlarını eğitimi
kullanarak biçimlendiriyor Eee iktidar değişirse Eee bu E yani
dünya politikasında milliyetçiliği kuvvet endiren bir şey var eğilim var
işte bu sen fobya dedikleri yabancı düşmanlığı Türkiye'de de Avrupa'daki
daha tehlikeli şekilde var Eee yani bu Suriyelilere afganlara
yönelik Eee şeye Eee yabancı düşmanlığına dönen
ve milliyetçilik olarak nitelendiriliyor bu da Bunlar
Eee aynı kalacağı için iktidarı biçimlendirme eee Eee gücü de devam
edecek Eee bu bu açıdan bakarsanız şeyin de yani buna Eee milliyetçiliğe
alternatif olacak şey de enternasyonalizm liberal değerlerdir Eee
dünyayla bütünleşmede bunun da çok Eee şansı
olmadığı görülüyor dünya giderek sertleşen bir çatışma içine giriyor
Eee ve bu sertleşen çatışma içinde Eee toplumdaki eğilimler de kendi
kabuğuna kapanmak devletini daha milliyetçi tavırlar Politikalar içinde görmek
şeklinde tecelli eder Eee şeyde devletler de iktidarlar da safları
sıklaştıralım arkamda sağlam durun diye bunu teşvik ederler Eee düşman üretmek Düşmanlar üzerinden
siyaset yapmak her zaman Eee iktidarların işini kolaylaştıran bir şeydir Yoksa da düşman icat ederler
Eee ben Eee Türkiye'de Eee yani iktidara
geldiğiniz zaman bir cephaneniz oluyor cebinizde eteğimdeki taşları döküyorsunuz bitiriyorsunuz Eee ben Eee
iktidarda islamcılığın da muhafazakarlığın da tükendiğini düşünüyorum Eee yeni gelen iktidar
cepleri dolu olarak gelecek Eee alternatifleri topluma sunacak onları deneyecek Eee
tepkiler alacak Ona göre biçimlere Eee ama milliyetçi muhafazakarlık Eee
itibardan düştü yani muhafazakarlık artık devlet imkanlarını kullanarak
zenginleşmek gibi bir şey olarak anlaşılıyor pahalı lüks şatafatlı
camiler olarak anlaşılıyor Eee dinin çok aşırı derecede
eee banal bir şekil siyasete alet edilmesi olarak anlaşılıyor bütün
bunlardan uzaklaşan bir iktidar yapısı çıkabilir fakat milliyetçiliğin şeyi yok milliyetçilik tam tersine
Eee daha genel daha kapsayıcı bir ideoloji olarak eğilim olarak daha
doğrusu varlığını devam ettirir Hocam bu sohbetimizin devamı bağlamında
bir soru daha sorayım şimdi Mevcut durumda görüyoruz ki Eee Türkiye
de orta sınıf son derece zayıflamış neredeyse yok olma noktasına gelmiş durumda Eee büyük bir yoksulluk ve fakirlik Eee
fen halde Eee etkisini gösteriyor Eee yine belirli bir grup e ciddi bir
şekilde zenginleşiyor Türkiye hiç bu kadar böyle bir manzara yaşamamıştı
bugüne kadar Aslında Eee böyle bir Eee ayrıma ayrışmaya ya da Eee dengesiz eee
bir şeye eee yürümemiş sosyal yapıya Eee siz Türkiye'nin geleceğini nasıl
görüyorsunuz eminim olumsuz bir okuma yapmak istemezsiniz Hani durduğunuz yer
adına Düşünüyorum bunu eee bir ön şey niyet okuma gibi
algılayabiliriz ama ama bu bence çok daha sanki riskli gibi yani hiç bu kadar
yoksullaşmak Eee bunun ileride ne olur Eğer bu böyle devam ederse ya da bunu
nasıl önleyecek Eee Türkiye'deki mevcut rejim önleyebilir mi yani eee işte yazın
yediğimiz hurmalar misali bu Türkiye'nin şey yatırımları büyük altyapı
yatırımlarının bedelini ödeyecek Türkiye Eee bunların hepsini Çünkü borçla yaptık
borçlanarak yaptık Yani ben Eee olumsuz bir Eee kanaat belirtmez siin diyorsunuz
ama öyle değil Eee oldukça kötümserin bu anlamda eee e Türkiye'yi herhalde 5
yıldan az olmamak üzere 10 yıla da çıkabilir ekonomik anlamda bir dar karanlık bir dönem bekliyor
Eee Çünkü Eee Türkiye Eee Finans sektörü
üzerinden Eee Özellikle o maliyedeki sihirbazlıklar ve Eee rant üzerinden bir
ekonomik refah dönemi yaşadı ve bunu geride bıraktı artık rant imkanları tükendi Eee şimdi reel sektörün üzerinde
üzerinden eee bir şey lazım performans lazım kendini gerçekleştirmesi lazım
ekonomik anlamda Bu da kolay değil bir de şeyi ödeyecek borçları ödeyecek Yani
biz bu köprülerin yolların parasını ödemeye devam edeceğiz Bir de ekonomik
olmayan rantable olmayan yatırımlar var Bu Şehir hastaneleri gibi Eee ciddi bir
şey bırakıyor geride bu iktidar dönemi sona erdiği zaman da eee Eee sonraki
nesillerin sırtına ciddi bir yük bırakıyor Eee şeyin orta sınıfın erimesi anlamında
yoksulla derinleşmesi anlamında da Türkiye'nin şartları çok iyi değil yani
eee bir karanlık gelecek bir karanlık dar bir yol görünüyor yani falcılık gibi
algılamayın bunu ekonomik göstergelerin hepsi bu istikamette ekonomi şey
kaldırmaz hayaldi ütopyayı o tür şeyleri kaldırmaz Eee dünyada da bu şekilde işliyor zaten
Bir de Eee dünyada çatışma eğilimleri çok kuvvetli bunun da
Eee maliyetleri Eee ekonominin üzerine bütün ekonomiler üzerine biniyor Türkiye
Eee savunma sanayini ayırıyor milli gelirinin Önemli bir kısmını Eee bunun
faydalarını görüyor fakat bunun ekonom maliyetini de ödemek zorunda bütün bunları yan yana getirdiğiniz zaman
sizin olumsuz dediğiniz Tablo netleşiyor bu açıdan çok iyimser şeyler
söyleyemem Tolga şimdi
Eee söyleşinin başında Eee münzer
Bey bu şeyi milliyetçiliği bir duygu durumu olarak Hani tanımladım
eee bir Devlet Kuşu yani şu an işte eski islamcılar
Eee ve milliyetçilerin başına konmuş bir devlet kuşu var şu an anlaşılan bu yarın
kimin başına konar herhalde Belli değil yani ben hani bu bunu biraz da böyle mi
anlamak lazım ama Eee siz Mesela şey diyorsunuz işte 20 21 yıllık iktidarın
muhtemelen 3 sene önce siyasi birikimi değil dar çıkar şebekelerinin Bürokratik
kafası iktidarı temsil ediyor Yani bu eee bir çıkar şebekesi
olarak Aslında Siz şu an devlette hakim olan güç olduğunu Bunlar Herhalde bize
Eee siyasal Eee temsil anlamında Eee Bu şey gibi Levye gibi en
kullanılabilir Eee siyasal çatı neydi işte muhafazakarlık ve milliyetçilik ama
altında hani benim size sorduğum şey buydu Eee siz kısmen sanki bunu böyle
paragrafların arasına Saklamışsın Hatta Tarik Çelek de de bunun üzerine de bir program yaptınız diye hatırlıyorum Evet
o programdaki dev muhteşemdi çıkarcı Tabii çıkarcı bir Bürokratik bir şeyden
bahsediyorsunuz bir çete gibi yani sanki yani bunlar Eee banın da sorusuna
ilişkilendirerek Hani milletin hem tarihine geçmişine hem geleceğine hem
ekonomisine Eee hem kültürüne hem inançlarına değerlerine çökmüş
Eee ve sömüren eee bir böyle bir şey sanki Eee anlıyorum Hatta Yani biraz
daha Absürt bir şey olsun Hani bu bir iş adamı kalktı televizyonda söyledi ya
Küfür argo bir küfürle yani sanki bu hali Eee yaşıyoruz yani böyle çok derin
komplolar devletin çok derin aklından ziyade eee anlad kadarıyla
eee bir şey böyle bir Eee
çeteleşme eee sürüyor diyelim Tulga bey Sizin
söylediklerinizi biraz objektif kavramlara dökeyim isterseniz Çünkü çok e siyasi bir şeydi
yaklaşımdır Şimdi Türkiye bir sistem değişikliği yaşadı Eee ve Eee
parlamenter sistem yerine Eee aslına bakarsanız Eee başkanlık sistemi de
değil geçilen sistem E Çünkü bunların hepsinin sınırları usulleri bellidir Eee
dünyada şey yok yeni bir siyasi sistem yok 2500 yıldır yok E Türk Türk usulü
Deniyor zaten Yani Türk usulü Tab yeri başkanlık sistemi dediler ya Türk usulü
tabiri de karikatür gibi duruyor orada şimdi Eee bakın
eee doğrudan doğruya yetki Yani bu tekelleşmek temerküz Tekelde
toplanmasıdır şeyin bütün Yetkilerin Eee Türkiye sistem değişikliğinden sonra
eee devletle Eee Seçimle gelen irade arasındaki
ilişkiyi dönüştürdü Bunun üzerinde çok fazla Durulmuyor iktidar farkında
olabilir iktidar kanadı farkında olabilir bu çok da iktidarın lehine olmadı
Eee daha önce yasama organı vardı milletvekilleri vardı Parti teşkilatları vardı Bunlar vatandaştan gelen talepleri
şeye taşırdı devlete devletin ilgili birimlerine taşırdı bir şekilde Eee
demokrasinin o şey tarafı yani halkla Eee devlet iktidarı arasındaki ilişki
iletişim Bunu sağlayan araçları iş başındaydı Bunlar Çalışıyordu bu sistem
değişikliğinden sonra devlet iktidarı tamamıyla bürokrasiye bırakıldı devlet
iktidarını kullanan güç milletvekilleri kullanamıyor Parti teşkilatları da kullananı
Eee doğrudan doğruya tek kişi tek kişinin elinde de değil yani aslına bakarsanız Cumhurbaşkanlığı sisteminde
cumhurbaşkanında değil şeylerde bürokratlardan Eee bakanların
hepsi bürokrat bakanların hiçbiri seçimle gelmiş adamlar değil yani Neticede Cumhurbaşkanı seçiyor onları
Fakat bunların formas bakış açıları da şey yani Bakın size çok
çarpıcı bir şey vereyim resim vereyim bunlardan hiçbiri vatandaşla konuşurken tebessüm edemiyor dikkat edin hiç
tebessüm eden Gülen e bakan göremiyorsunuz o Bakanlığın yani o
bürokrasinin şeyidir o refleksidir bürokratın bürokratın şeyden siyasetçiden farkı şudur bürokrat Eee
onu oraya getiren üstündeki amirine hizmet eder siyasetçi ise Siyasette
kalmak için halka hizmet etmek zorundadır yani yasama organının yerine
Siz şeyi koyduğunuz zaman Cumhurbaşkanlığı külliyesindeki Eee birimleri Eee koyduğunuz zaman işte
yasama organın da orada hazırlanan kanunları sadece yasallaştırmak la görevli bir birime dönüştürdüğünü zaman
Eee aslında Sadece Eee Yukarıyı memnun etmekle mükellef dar bir grubunu Egemen
hale getiriyorsunuz bir tür Bürokratik diktatörlük yaratıyorsunuz Türkiye
sistem değişikliğinden sonra buna geçti Eee bu Bürokrasi halka hizmet etmez
halktan gelen eğilimleri taşımaz ve en önemlisi de bakın
denetleyemez milleti milleti tehdit mi görür Çünkü biz öyle biliyoruz yani eee
esnafı hırsız vergi kaçıran vatandaşı hep yasakları şeyi ihlal eden ya
Bürokrasi kafası biraz masa başında böyle çalışır diye biliyoruz yani kendini korumacı ve dolayısıyla halk şey
gibi rakip Biz Devleti bunlara karşı nasıl koruruz hatta nasıl onların üzerine hakim kılarız böyle mi bu
söylediğiniz tamamıyla doğru yani şeyin bürokrasinin ruhunu yansıtan Önemli bir şeydir cephesidir bu eee Fakat aynı
zamanda şeyden siyasetçiden farkını anlatıyorum ben Eee yani Eee bürokrat Eee bürokratın
vatandaşa Eee vatandaştan alacağı bir Eee geri dönüşten iyi bir geri dönüşten
hiçbir karı yoktur vatandaş memnun olmuş olmamış hiç umurunda değildir memnun
edeceği tek kişidir onun onu oraya getiren kişi Şimdi bu şeyi çökertti
sistemi işlemez hale getirdi Türkiye'de siyasal sistemin çok ciddi manada yani
objektif olarak bakın şey olarak değil eleştirel anlamda değil objektif olarak baktığınız zaman vatandaştan gelen
talepleri şeye taşıyacak devlet iktidarını kullananlara taşıyacak devlet iktidarı da Eee onun ihtiyaçlarını
karşılamak üzere politika üretecek bu işlemiyor Türkiye'de şu anda bu işlemiyor iktidarın çektiği
sıkıntının temel sebebi de bu bunun Eee Ben büyük ölçüde farkında olduklarını
düşünüyorum ama Eee o iktidar temerküzü dediğim Eee iktidarın Tekelde
toplanmasını Eee gündeme getirdiği için kimse üzerinde duramıyor Bakın bu eee
işte Zonguldak'ta Eee Erzincan'da yaşanan o maden faciaları buna benzer
şeyler eee Aslında bu sistem değişikliği sonrasında ortaya çıkan sakatlıkların
ürünü onlar öncesinde Bürokrasi Eee yerel ölçüde de denetleniyorda
mühendisleri eee bir denetim altındaydı şimdi o işlemiyor merkezli her şey
merkezin gidip de onu denetlemesi mümkün değil Bürokrasi sizin verdiğiniz örnekte
Eee nasıl onu oraya getiren Eee ne karşı sadece şey yapıyorsa onun altındaki de
ona karşı öyledir bu zincirleme gider oraya kadar ve buradan denetim çıkmaz
buradan rasyonel bir yönetim çıkmaz Eee ve bu tür şeyler felaketlerle ve
kazalarla sık sık karşılaşırsınız buradan şey de çıkmıyor bakın ekonominin çöküşü de Türkiye'de sistem
değişikliğinden sonra oldu ekonomi Eee Sistem değişti o
ekonominin basit şeyleri vardır Eee hassasiyetleri vardır o şeyi alır
işareti alır sinyali alır onu taşır ona uygun politika üretir bunları yapamadı
ekonomi birdenbire 2017 sistem değişikliğinden sonra ekonomik parametrelerin tamamı kötüleşmeye
başladı Bu da tesadüf değil Evet daha sorulara
geçmeden Eee Mümtazer Bey'in şu Kitap kitaplarını da bir ekrana verelim de
evet Eee son dönemde yazdığı değil mi Mümtazer hocanın Eee Evet bu 1978 benim
fakülteden mezun olduğum tarih 1978 yılını Mart ayını ele alan bir roman
Eee o şiddetin çok yoğun olduğu dönemlerde Evet Eee Evet
Eee Roman değil mi roman roman Evet siz daha önce roman Yazmıyordu herhalde Evet
ş romancı romancı mı diyeceğiz size yani eee Tolga Bey okur beğenirseniz
diyebilirsiniz [Kahkaha] [Müzik]
Eyvallah Hoca şey yaptı görev verdi alacağız kitapları Aynen aynen tabii E
ben de ben de size takdim ederim merak etmeyin Zakir de bir roman Eee
cezaevinde uzun süre Kaldım orada şey imkanı yok Eee kaynaklara ulaşma yani
eee alıştığım şekilde akademik çalışma yürütme imkanı yok Eee müracaat
edeceğiniz tek şey hayal gücünüz O yüzden Roman çıkıyor ortaya bunun
eseri hocam bir kitabınız daha var Evet bu e milliyetçiliği Eee küçük Türkiye
milliyetçiliğidir Bu kitabın alt başlığı eee Eee yani etnosentrizm yaparsanız bu
ülkede yaşayan insanları dışlarsan Eee yaptığınız milliyetçilik türü Türkiye'yi
küçülten bir milliyetçiliktir o yüzden küçük Türkiye milliyetçiliğidir bunu da ancak mankurtlar yapar gibi bir mantığa
dayanıyor Bir de hocam şey var Eee alanınızla ilgili çıkarttığınız bir
kitap var Evet siyaset bilimine giriş kitabı bu eee bir zamanlar çok fazla
Üniversitede okutuluyordu ders kitabı olarak pratik kullanışlı yani konuya
hakim olmak isteyenler için temel konuların tamamını ihtiva eden bir
kitaptır Evet hocam Şimdi biz bu programı Eee yapma kararı alınca işte
bir afiş hazırladık ve Eee ilan ettik programı Eee Bazı
arkadaşlarımız bizi Eee Çok cesur olmakla Eee nitel di Tabii ki neden Cesur
olmakla sizin işte yaşadığınız süreç ve Eee mahalledeki Tabiri caizse öyle
diyelim mahalledeki Eee imajlarını da alakalı bir şeydi bu bir geri dönüştü
belki kimi zaman Serzeniş tadındayım Ben Eee buradan yola çıkarak özel bir soru
soracağım ama cevap vermeyebilir siniz hocam yani eee bu tamamıyla sizin Eee
takdirinize bıraktığım bir konu eee nasıl cevaplarsanız da başımızın üstüne
koyarız eee bir röportajını da şöyle bir şey söylüyorsunuz yaşadıklarınız yola
çıkarak Eee iki grubun Eee iktidar mücadelesinin
bedelini ödedik diyorsunuz ve bize Bedel ödeten lere Bedel ödeteceğiz Eee gibi
bir cümleniz var Tam hatırlayamıyorum şu anda Eee dediğim gibi özel bir soru bu
cevaplayabilirsiniz herhalde çoğun değil dedi hoca derse bir çoğ bir grup gibiş Evet
ödeteceğim dedi Doğru burada şunu sormak istiyorum Nasıl ödetecek ve ikincisi
Korkmuyor musunuz millet bize sorduğu gibi Korkmuyor musunuz diye sorunca biz
de size soralım nasıl edeceksiniz ve Korkmuyor musunuz e Evet
yani Tolga Bey'in şeyi ikazı önemliydi bireysel olarak söylediğim bir
şey bu Çünkü ben tek başına bir adamım Eee herhangi bir gruba herhangi bir
siyasi partiye herhangi bir cemaate Eee bağlı değilim Eee arkamda
Eee beni besleyen destekleyen bir grup yok şimdi Eee ve eee bir iktidar
rekabeti bir iktidar kavgası Her neyse Eee bunlar Türkiye'de konuşulacak
tartışılacak ve yaklaşıyor zaten belirgin hale geliyor
Eee ben bu iktidar rekabetinde bir haksızlığa uğradım hukuksuzluğa uğradım
Eee bu eee tek başıma bir adamım ama bireysel
olarak elinde sadece kalemi olan bir adama yapılan bu haksızlığın peşine
düşmezsem bu haksızlığı yapanlardan hesap Sormazsam onların burunlarından
fitil fitil getirmezsem bu haksızlığı bana yapanları yapanların yapanlardan
hesabı Sormazsam O zaman ben elimdeki kaleme ihanet etmiş olurum Yani
Türkiye'de benden sonra da elinde kalemiyle yaşayacak olan insanların benzer şeylerle karşılaşmaması lazım
Eee sadece yazdığım yazılardan yargılandım ki yazdığım yazıların
Hiçbiri de yazıldığı zaman herhangi bir Eee soruşturmaya konu edilmemişti Eee ve
cezalandırılmak susturulmak üzere hapiste tutuldu uzun süre
Eee bunun hesabını sormak zorundayım kendi adıma değil
Eee korku dağları bekliyor herkes korkuyor böyle dönemlerde herkes korkuyla geri çekiliyor
Eee korkarak nereye kadar varacaksınız yani eee Ölümden Öte Köy Yok bu çok
bilinen bir söz ama Eee kalemin namusu vardır kalemin şerefi
vardır bunu da Eee elindeki imkanı gücü sizi hapse
tıkmak için kullananlara karşı e muhafaza etmeniz ve korumanız gerekir
Eee yani benim yarama parmak bastınız Eee sağ olursam
Eee bakın hukuk bahsettiğim şey hukuk Yani gidip birinin kafasına silah
dayayıp mermi sıkmayacak Tabii ki Tabii E gidip birinden İntikam almayacağım
yolunu gözleyip E ondan sonra Ayağına çelme TM anlamında hesap
soraca ve ne kadar fazla hukuksuzluk yapıldıysa ödeyecekleri Bedel de o kadar
fazla
olur sel sorularda çok fazla bir şey var mı
bir bakalım Merak ediyorum şu
soruyu üniversite oda arkadaşı olduğunu duymuştum diyor yolcu mahlaslı arkadaşımız Türköne'nin yaşadığı süreçte
Bostancı bir defa bile açıklama yapmadı kırgınlığı var mı sorar mısınız di
Eee Evet yani Naci benim kankamdan Aynı kaderi paylaştık Eee 12
Eylül'den sonra Aynı davadan
yargılandıkları paralel yürüdü Naci benim Kadim dostumdur ona benzer eski
dostlarım var Eee şimdi de bir üniversitenin rektörlüğün yapıyor Eee
Siyasette çok başarılı oldu doğrusunu isterseniz gelip bana sorsaydı Eee ya
sana sahip çıkayım Eee işte senin için bir şeyler söyleyeyim deseydi yapma derdim
Eee çünkü onun e girdiği yürüdüğü yolda
Eee yapması gereken şeyler vardı çok da başarılı oldu Eee namuslu bir adamdır
onurlu bir adamdır Eee ben herhangi bir kırgınlık ve E şey
hissetmiyorum hissetmedim Naciye karşı Eee
ve şeyden sonra cezaevinden çıktıktan sonra da kaldığımız yerden muhabbetimizi
sürdürüyoruz Kırgınlık yok o zaman Kırgınlık yok evet
evet başka soru getirecek misin Baha yok bence yeterli diyorum bir buçuk saat
oldu Çok da fazla yormayalım hocayı Eee Baha Bey sigara içiyorsunuz ve siz
yorulmuş görünüyorsunuz kaçmıyor oaman O zaman
şöyle şöyle bitirelim Eee ya bu benim devamlı merak ettiğim aradığım bir şey
rahmetli merhum Alev Alatlı la da konuşurken bu bahis geçmişti münzer bey siz ben
kendimi hakikaten bir arkadaşınız da yazmış bu söyleşinin ana cümlesi ben Türkiye'ye
aitim hakikaten Başlığa çekilecek bir cümle yani kendini buraya ait olan biz
de işte Baha olsun Ben olsun 90'lı 80'li yıllarda Türkiye'nin çocukları Hani
Cemil merçin bu ülkenin çocuklarından mülhem olarak bu ülkenin
çocukları olarak gören Herkes buraya bir borcu var Eee ve Eee Dolayısıyla
Eee Alev Han'ın Mesela bir Rus devlet aklının Her ne olursa olsun
yani çeteler işte siyasal savrulmalar ne olursa olsun orada bir entelektüel
düşüncenin bir Aydın tavrının olduğunu ve dolayısıyla bir devlet haklının eee
bir şekilde Eee çalıştığını doğ ister Sovyet olsun
ister Çarlık olsun ister şimdi Kün dönemi olsun söyledi ve ben Eee
kendisine o zaman sordum yani biz biz bizde bu yok mu yoksa daha ne kadar
beklemek lazım yani eee Çünkü Eee Türkiye'de devlet
hakikaten sistemi şu an çalışmaz bir durumda Yani çalışmıyor Eee sıkıntılar
çok büyük Baha iyimserlikle Hani siz belki kötü öngörüde bulunmak istemez
dedi ama Eee yani eee burada kalkıp çok da hayalperestlik de çok gerek yok yani
nasıl görüyorsunuz Yani bu topraklara eee şey olan borçlu birisi olarak yani
Türkiye aydınları entelektüelleri Eee sınıfta kaldılar mı ya da böyle bir
potansiyel söz konusu mu Eee böyle bir bağlayalım O zaman söyle yani bu yel
değirmenleriyle savaşan Eee Don Kişot durumuna düşerdi çoğu Eee eee o anlamda
Haklılar Eee kendilerini korudular korumaya çalıştılar Fakat bu ülkenin
kaderi Eee yani bir nazım Hikmet'i düşünün bir Kemal Tahir'i Sabahattin Ali'yi Orhan
Kemal'i düşünün Eee Türkiye'de biraz
Eee eline kalem almayı deneyen herkes şeye uğramış Eee devletin gadrine
uğramış eee Eee bundan çok kaybettiğimiz şey var Yani bu sadece bizim hanemize zarar
olarak yazılmıyor fakat Tolga Bey sizin sorunuzda da var Sanıyorum Benim
anlattıklarım da da var sizde de bende de o devlet aklının Aslında ne olması gerektiğine dair çok sağlam bir
Eee yargı var kanaat var Eee yani kör topal aksayarak ekse yerek
Eee ve iktidarların yalamaları ile birlikte birçok şeyi kaybederek
ilerliyoruz ama en nihayetinde Eee sizin benim aklımız Eee ve bu
toplumun toplumu da milleti de hafife almamak lazım milletin sağduyusu
Eee sonunda geliyor Egemen oluyor Eee
yani dünyada bu devlet hakkına sahip olan 56 tane devlet vardır onlardan
birisidir Türkiye eee Eee ruslarda varsa
bizde de vardır Merak etmeyin Bir de şey ilginç Eee siz şöyle demişsiniz sol
ideoloji de kendisini geliştirmeye başladı solun ideolojik yeniden doğuş
yaşadığını gözlüyorum diyorsunuz Eee bu şeyde solda derinden Derine Eee
bazı şeyler var tartışmalar var onları ben takip ediyorum bu ayrı bir program konusu ama tamam o
zaman girmeyelim söz alalım ayrı bir program olur aslında şeyi de
konuşabiliriz O program içerisinde Türkiye'deki kadın hareketlerinin çok derinden ve Tabandan yükseldiğini
görüyoruz Kürt hareketinin hakeza öyle çok entelektüel bir arka planları var Her şey bunları takip ediyor solu takip
ediyor Kürt hareketlerini siyasal hareketini takip ediyor Bir de buna ayıralım yani milliyetçi muhafazakar la
ilgili bir program kısmen de gerçekleştirdik ama olur mu mümkün mü Bir de burayı okuyalım
bu şeye bu usule yeni yeni alışıyorum Fakat çok rahat bir usul yani çayınızı
içiyorsunuz evdesiniz bir sakıncası yok olur
eyvallah ey Tolga ben açtım Sen kapat Evet
E bu akşam Mümtaz Türköne ile Türkiye yüzyılında rejimin milliyetçi
muhafazakar kodlarını konuştuk ben kendi adıma söyleyeyim Eee
yani konuşmanın içeriği bir kenara Eee Mümtazer Türk ile konuşmak benim
için bir keyifti kendisine minnettarım Eee Teşekkür ederim açık yürekliliği
için Eee Türk aydının Türkiye'deki aydınların ve entelektüellerin kendisiyle Eee hesaplaş bilmesi
adına çünkü ben onu sordum Mümtaz Bey'e Eee yani Siz önceden böyle mi
düşünüyordun Yani insanın değişim ve dönüşüme açık olması kadar önemli bir şey yok ve biz bunu Eee müntezir Bey de
kendisiyle hesaplaşması adına Bu cesareti eee bir kez daha şahit olduk
Eee Dolayısıyla kendisine tekrar Eee teşekkür ediyorum eee bir sonraki pazar
akşamı düşünce hukukunda yine birlikte olmak ümidiyle Eee Hayırlı geceler
efendim Hayırlı geceler Çok teşekkür ediyorum Tolga Bey Baha Bey güzel bir
sohbet oldu hocam çok istifade ettik ekranımı değer kattınız Biz teşekkür
ediyoruz Eee Hayırlı akşamlar İyi akşamlar olsun
